services:
  reeldocs:
    build:
      context: .
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reeldocs.rule=Host(`docs.respeak.io`)"
      - "traefik.http.routers.reeldocs.entrypoints=websecure"
      - "traefik.http.routers.reeldocs.tls.certresolver=myresolver"
      - "traefik.http.services.reeldocs.loadbalancer.server.port=3000"
    ports:
      - "3000:3000"
