#!/usr/bin/env bash
set -euo pipefail

usage() {
  echo "Usage: $0 --dir <docs-dir> --slug <slug> --label <label> --video-id <youtube-id>"
  echo ""
  echo "Add generated docs to the gallery site."
  echo "Accepts both .md (markdown) and .mdx output from reeldocs."
  echo ""
  echo "  --dir       Directory containing .md or .mdx files from reeldocs output"
  echo "  --slug      URL-safe name (e.g. langdock-workflows)"
  echo "  --label     Sidebar label (e.g. \"Langdock Workflows\")"
  echo "  --video-id  YouTube video ID (e.g. JS4PhZ36u8U)"
  exit 1
}

DIR="" SLUG="" LABEL="" VIDEO_ID=""
while [[ $# -gt 0 ]]; do
  case $1 in
    --dir)      DIR="$2"; shift 2;;
    --slug)     SLUG="$2"; shift 2;;
    --label)    LABEL="$2"; shift 2;;
    --video-id) VIDEO_ID="$2"; shift 2;;
    *) usage;;
  esac
done

[[ -z "$DIR" || -z "$SLUG" || -z "$LABEL" || -z "$VIDEO_ID" ]] && usage

ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
GALLERY_RAW="$ROOT/gallery/$SLUG"
GALLERY_SITE="$ROOT/packages/gallery/src/content/docs/$SLUG"

# Detect input format
if ls "$DIR"/*.mdx &>/dev/null; then
  EXT="mdx"
elif ls "$DIR"/*.md &>/dev/null; then
  EXT="md"
else
  echo "Error: No .md or .mdx files found in $DIR" >&2
  exit 1
fi

echo "Adding '$LABEL' to gallery (from .$EXT files)..."

# 1. Copy raw files to gallery/ (as .mdx with source blockquote for first file)
mkdir -p "$GALLERY_RAW"

if [[ "$EXT" == "mdx" ]]; then
  # MDX input: copy as-is, add source attribution to first file (by sidebar_position)
  cp "$DIR"/*.mdx "$GALLERY_RAW/"
  FIRST_RAW=$(grep -l 'sidebar_position: 1' "$GALLERY_RAW"/*.mdx 2>/dev/null | head -1)
  if [[ -n "$FIRST_RAW" ]]; then
    TMPFILE=$(mktemp)
    # Insert source line after frontmatter closing ---
    awk -v url="https://www.youtube.com/watch?v=$VIDEO_ID" '
      /^---$/ && seen { print; print ""; print "> **Source:** Generated by [Reeldocs](https://github.com/respeak-io/reeldocs) from [YouTube](" url ")"; seen=2; next }
      /^---$/ && !seen { seen=1 }
      { print }
    ' "$FIRST_RAW" > "$TMPFILE"
    mv "$TMPFILE" "$FIRST_RAW"
  fi
else
  # MD input: copy as-is, add source attribution to first file (alphabetically)
  cp "$DIR"/*.md "$GALLERY_RAW/"
  FIRST_RAW=$(ls "$GALLERY_RAW"/*.md | head -1)
  if [[ -n "$FIRST_RAW" ]]; then
    TMPFILE=$(mktemp)
    head -1 "$FIRST_RAW" > "$TMPFILE"
    echo "" >> "$TMPFILE"
    echo "> **Source:** Generated by [Reeldocs](https://github.com/respeak-io/reeldocs) from [YouTube](https://www.youtube.com/watch?v=$VIDEO_ID)" >> "$TMPFILE"
    tail -n +2 "$FIRST_RAW" >> "$TMPFILE"
    mv "$TMPFILE" "$FIRST_RAW"
  fi
fi

# 2. Create Starlight MDX files
mkdir -p "$GALLERY_SITE"

if [[ "$EXT" == "mdx" ]]; then
  # MDX input: transform frontmatter (sidebar_position → sidebar.order), add YouTube embed to first
  for f in "$DIR"/*.mdx; do
    BASENAME="$(basename "$f")"
    OUTFILE="$GALLERY_SITE/$BASENAME"
    POSITION=$(grep 'sidebar_position:' "$f" | awk '{print $2}')

    # Extract title from frontmatter
    TITLE=$(grep '^title:' "$f" | sed 's/^title: *//; s/^"//; s/"$//')

    # Get content after frontmatter
    BODY=$(awk '/^---$/{c++; next} c>=2' "$f")

    {
      echo "---"
      echo "title: \"$(echo "$TITLE" | sed 's/"/\\"/g')\""
      echo "sidebar:"
      echo "  order: $POSITION"
      echo "---"

      if [[ "$POSITION" == "1" ]]; then
        echo "import YouTubeEmbed from '../../../components/YouTubeEmbed.astro';"
        echo ""
        echo "<YouTubeEmbed videoId=\"$VIDEO_ID\" />"
        echo ""
        echo "> Generated by [Reeldocs](https://github.com/respeak-io/reeldocs)"
      fi

      echo ""
      echo "$BODY"
    } > "$OUTFILE"
  done
else
  # MD input: create MDX from scratch (alphabetical order)
  ORDER=1
  for f in "$DIR"/*.md; do
    BASENAME="$(basename "$f" .md)"
    TITLE="$(head -1 "$f" | sed 's/^# //')"
    OUTFILE="$GALLERY_SITE/$BASENAME.mdx"

    {
      echo "---"
      echo "title: \"$(echo "$TITLE" | sed 's/"/\\"/g')\""
      echo "sidebar:"
      echo "  order: $ORDER"
      echo "---"

      if [[ $ORDER -eq 1 ]]; then
        echo "import YouTubeEmbed from '../../../components/YouTubeEmbed.astro';"
        echo ""
        echo "<YouTubeEmbed videoId=\"$VIDEO_ID\" />"
        echo ""
        echo "> Generated by [Reeldocs](https://github.com/respeak-io/reeldocs)"
      fi

      echo ""
      # Skip the H1 line, output the rest
      tail -n +2 "$f"
    } > "$OUTFILE"

    ORDER=$((ORDER + 1))
  done
fi

RAW_COUNT=$(ls "$GALLERY_RAW"/*.$EXT 2>/dev/null | wc -l | tr -d ' ')
SITE_COUNT=$(ls "$GALLERY_SITE"/*.mdx 2>/dev/null | wc -l | tr -d ' ')

echo "  Copied $RAW_COUNT files to gallery/$SLUG/"
echo "  Created $SITE_COUNT MDX files in packages/gallery/src/content/docs/$SLUG/"
echo ""
echo "Next steps:"
echo "  1. Add sidebar entry to packages/gallery/astro.config.mjs:"
echo "     { label: \"$LABEL\", autogenerate: { directory: \"$SLUG\" } }"
echo "  2. Preview: pnpm --filter gallery dev"
